---
- include_vars: "{{ item }}"
  with_first_found:
     - "{{ ansible_os_family }}-{{ ansible_distribution_major_version}}.yml"
     - "{{ ansible_os_family }}.yml"

- include_tasks: login-defs.yml

- yum: name=epel-release

- name: install restuser
  include_tasks: "{{ item }}"
  with_first_found:
     - "install-{{ ansible_os_family }}-{{ ansible_distribution_major_version}}.yml"
     - "install.yml"

- template: src=restuser.service.j2 dest=/etc/systemd/system/restuser.service

- command: systemctl daemon-reload

- name: start restuser
  service: name=restuser state=restarted enabled=yes

- name: wait for restuser socket to exist
  wait_for: "path=/var/run/restuser.sock"
